// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QR_Code_Prototype.Data;

#nullable disable

namespace QR_Code_Prototype.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530041849_MergeMainAndApiModels")]
    partial class MergeMainAndApiModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageReference")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.QrCodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("QrCodeRecords");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.QrScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QrCodeRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeRecordId");

                    b.ToTable("QrScanEvents");
                });

            modelBuilder.Entity("QR_Code_Prototype.Models.PackagePassModel", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackagePass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageID");

                    b.ToTable("PackagePass");
                });

            modelBuilder.Entity("QR_Code_Prototype.Models.RolesModel", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QR_Code_Prototype.Models.UserModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.QrCodeRecord", b =>
                {
                    b.HasOne("QR_Code_Prototype.Domain.Entities.Package", "Package")
                        .WithMany("QrCodes")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.QrScanEvent", b =>
                {
                    b.HasOne("QR_Code_Prototype.Domain.Entities.QrCodeRecord", "QrCodeRecord")
                        .WithMany("ScanEvents")
                        .HasForeignKey("QrCodeRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QrCodeRecord");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.Package", b =>
                {
                    b.Navigation("QrCodes");
                });

            modelBuilder.Entity("QR_Code_Prototype.Domain.Entities.QrCodeRecord", b =>
                {
                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
